### ISSUE TITLE
missing module error on 'ionic serve' after local install

### ISSUE THREAD

**Issue by rodmachen** [rodmachen/slacker-server#2]
Linux user gets this error upon 'ionic serve' in the client folder after 'npm install.'

App still appears to be fully functional.

```
ionic $ module.js:339
    throw err;
    ^

Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/doug/dev/projects/slacker-movie-quiz/client/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:39:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by thomas-tewelde** [comment]
hi did u fix this yet
